apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: paymybuddy

# Opaque = type générique pour stocker des données sensibles arbitraires
# Les valeurs en stringData sont automatiquement encodées en base64 par Kubernetes
type: Opaque

stringData:
  # Mot de passe root MySQL - utilisé uniquement par MySQL en interne
  # ⚠️ Doit correspondre à MYSQL_ROOT_PASSWORD dans mysql-deployment.yaml
  mysql-root-password: password

  # Utilisateur dédié à l'application PayMyBuddy (non root)
  # utilisé par l'application pour la connexion JDBC
  mysql-user: "paymybuddy_user"

  # Mot de passe de l'utilisateur dédié - référencé par PayMyBuddy pour la connexion JDBC
  mysql-password: "paymybuddy_password"

  # Nom de la base de données
  # ⚠️ Doit correspondre au CREATE DATABASE dans mysql-configmap.yaml
  mysql-database: "db_paymybuddy"
